// Central Blueprint section config used across the app
import {
  Shield, FileText, Home, HeartHandshake, Compass, Users,
  Sparkles, Briefcase, ClipboardList, Laptop, Stethoscope, HandCoins, House,
} from "lucide-react";

export const SECTIONS = [
  { key: "requirements", label: "Release Requirements", short: "Requirements", icon: Shield,
    blurb: "Supervision, check-ins, court dates, testing, classes, fees.", accent: "gold",
    checklist: ["Requirements & conditions", "Required check-ins", "Drug-testing requirements", "Court dates / hearings",
      "Required classes / programs", "Community-service hours", "Fees / fines / restitution", "Curfew / other requirements"] },
  { key: "documents", label: "Document Center", short: "Documents", icon: FileText,
    blurb: "IDs, court papers, addresses, bank setup, employment docs.",
    checklist: ["Release documents", "Court documents", "Probation / parole documents", "State ID / driver's license",
      "Social Security card", "Birth certificate", "Mailing address", "Phone / email",
      "Bank-account setup", "Healthcare / insurance info", "Employment documentation"] },
  { key: "independent-living", label: "Independent Living", short: "Living", icon: Home,
    blurb: "Housing, utilities, transport, food, budgeting, banking.",
    checklist: ["Housing", "Utilities", "Transportation", "Food & groceries", "Budgeting", "Banking", "Community resources"] },
  { key: "wellness", label: "Recovery & Wellness", short: "Wellness", icon: HeartHandshake,
    blurb: "Education & organization only — not treatment or crisis care.",
    checklist: ["Habit-change education", "Personal journal & tracking", "Triggers & coping strategies",
      "Stress & emotional awareness", "When to reach a professional"] },
  { key: "life-skills", label: "Decisions & Life Skills", short: "Life Skills", icon: Compass,
    blurb: "Decisions, coping, conflict, boundaries, spotting scams.",
    checklist: ["Decision-making", "Consequences / trade-offs", "Coping skills", "Conflict resolution",
      "Boundaries", "Problem solving", "Handling setbacks", "Recognizing scams / manipulation"] },
  { key: "support-circle", label: "Support Circle", short: "Support", icon: Users,
    blurb: "Trusted people, categorized by how they can help.",
    checklist: [] },
  { key: "identity", label: "Identity & Confidence", short: "Identity", icon: Sparkles,
    blurb: "Strengths, values, goals, confidence, growth mindset.",
    checklist: ["Strengths & values", "Goals", "Career interests", "Skills / talents", "Confidence & self-talk",
      "Handling rejection", "Growth mindset", "Wins journal"] },
  { key: "employment-readiness", label: "Employment Readiness", short: "Job Prep", icon: Briefcase,
    blurb: "Careers, resume, interviews, professional communication.",
    checklist: ["Career exploration", "Job-search strategies", "Resume", "Interview prep",
      "Professional communication", "Workplace expectations", "Certifications / training"] },
  { key: "employment-record", label: "Employment & Income", short: "Income", icon: ClipboardList,
    blurb: "Employers, hours, pay — you control what is shared.",
    checklist: [] },
  { key: "digital-readiness", label: "Digital Life Readiness", short: "Digital", icon: Laptop,
    blurb: "Email, passwords, forms, video interviews, security.",
    checklist: ["Email & communication", "Password / security basics", "Online applications",
      "Scanning / uploading documents", "Video interviews", "Digital signatures", "Online banking basics",
      "Privacy / scam awareness"] },
  { key: "health-hub", label: "Health Hub", short: "Health", icon: Stethoscope,
    blurb: "Medications, appointments, records, insurance, wellness.",
    checklist: [] },
  { key: "benefits-hub", label: "Benefits Hub", short: "Benefits", icon: HandCoins,
    blurb: "Benefits education, active benefits, documents, contacts.",
    checklist: [] },
  { key: "home-hub", label: "Home Hub", short: "Home", icon: House,
    blurb: "Housing stability, utilities, maintenance, safety, reminders.",
    checklist: [] },
];

export const SECTION_BY_KEY = Object.fromEntries(SECTIONS.map((s) => [s.key, s]));
